name: Test container image build

on:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'eds-book'
    steps:

    # For biggish images, github actions runs out of disk space.
    # So we cleanup some unwanted things in the disk image, and reclaim that space for our docker use
    # https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
    # and https://github.com/easimon/maximize-build-space/blob/b4d02c14493a9653fe7af06cc89ca5298071c66e/action.yml#L104
    # This gives us a total of about 52G of free space, which should be enough for now
    - name: cleanup disk space
      run: |
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        df -h

    - name: checkout files in repo
      uses: actions/checkout@main

      # Set quay image name
    - name: Get properties from the config file
      id: config_file
      uses: notiz-dev/github-action-json-property@release
      with:
        path: '.github/config.json'
        prop_path: 'quay_image'

    - name: Build the image and push it if `NO_PUSH` disabled
      uses: jupyterhub/repo2docker-action@master
      with: # make sure username & password/token matches your registry
        NO_PUSH: "true"
        DOCKER_REGISTRY: "quay.io"

        # Uncomment and modify the following line with your image name. a
        IMAGE_NAME: ${{steps.config_quay.outputs.prop}}

    # Lets us monitor disks getting full as images get bigger over time
    - name: Show how much disk space is left
      run: df -h
